apiVersion: apps/v1
kind: Deployment
metadata:
    name: talk-booker-back-end
    labels:
        app: talk-booker-back-end
spec:
    replicas: 1
    selector:
        matchLabels:
            app: talk-booker-back-end
    template:
        metadata:
            name: talk-booker-back-end
            labels:
                app: talk-booker-back-end
                role: back-end
                env: local
        spec:
            containers:
            - name: talk-booker-back-end
              image: talk-booker-back-end
              volumeMounts:
                - name: credentials
                  mountPath: "/etc/credentials"
                  readOnly: true
              imagePullPolicy: Never
              env:
                - name: SPRING.DATA.MONGODB.URI
                  valueFrom:
                    secretKeyRef:
                        name: mongodb
                        key: uri
              ports:
              - containerPort: 8080
            volumes:
            - name: credentials
              secret:
                secretName: mongodb
                