apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  uri: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmQyMDIwQGRlbW8tY2x1c3Rlci1zaGFyZC0wMC0wMC1iejBxdi5nY3AubW9uZ29kYi5uZXQ6MjcwMTcsZGVtby1jbHVzdGVyLXNoYXJkLTAwLTAxLWJ6MHF2LmdjcC5tb25nb2RiLm5ldDoyNzAxNyxkZW1vLWNsdXN0ZXItc2hhcmQtMDAtMDItYnowcXYuZ2NwLm1vbmdvZGIubmV0OjI3MDE3L3Rlc3Q/c3NsPXRydWUmcmVwbGljYVNldD1kZW1vLWNsdXN0ZXItc2hhcmQtMCZhdXRoU291cmNlPWFkbWluJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
